<a href="https://colab.research.google.com/github/deboraafr/Bigdata/blob/main/Aula4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 4

Pandas

In [1]:
import pandas as pd
import numpy as np

Criação de matriz:

In [3]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

criação do dataframe:

In [4]:
meuDf = pd.DataFrame(meusDados)

para verificar o tipo:

In [5]:
type(meuDf)

pandas.core.frame.DataFrame

para visualizar:

In [6]:
meuDf

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Criação do index:

In [40]:
indice = ['Linha ' + str(i) for i in range(4)]

Criação de colunas:

In [41]:
colunas = ['coluna ' + str(i) for i in range(3)]

Mais organizado

In [12]:
df2 = pd.DataFrame(data= meusDados, index= indice, columns= colunas)
df2

coluna 0  coluna 1  coluna 2
Linha 0         1         2         3
Linha 1         4         5         6
Linha 2         7         8         9
Linha 3        10        11        12

forma abreviada:

In [13]:
df2 = pd.DataFrame(meusDados, indice, colunas)
df2

coluna 0  coluna 1  coluna 2
Linha 0         1         2         3
Linha 1         4         5         6
Linha 2         7         8         9
Linha 3        10        11        12

Criar Data Frame manualmente:

In [39]:
df3 = {'coluna0': {'Linha0':1, 'Linha1':4, 'Linha2': 7},
       'coluna1': {'Linha0':2, 'Linha1':5, 'Linha2': 8},
       'coluna2': {'Linha0':3, 'Linha1':6, 'Linha2': 9}
       }
df3

{'coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
 'coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
 'coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [43]:
df4 = pd.DataFrame (df3, indice, colunas)
df4

coluna 0 coluna 1 coluna 2
Linha 0      NaN      NaN      NaN
Linha 1      NaN      NaN      NaN
Linha 2      NaN      NaN      NaN
Linha 3      NaN      NaN      NaN

In [19]:
df3 = pd.DataFrame(df3)
df3

coluna0  coluna1  coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

Concatenação

In [20]:
df4 = pd.concat ([meuDf, df2, df3])
df4

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
0         1.0   2.0   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0   5.0   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0   8.0   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0  11.0  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN   NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN   NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN   NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN   NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN   NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN   NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN   NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
Linha 0      NaN  
Linha 1      NaN  
Linha 2      NaN  
Linha 3      NaN  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

isnull:

In [21]:
df4.isnull()

0      1      2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
0        False  False  False      True      True      True     True     True   
1        False  False  False      True      True      True     True     True   
2        False  False  False      True      True      True     True     True   
3        False  False  False      True      True      True     True     True   
Linha 0   True   True   True     False     False     False     True     True   
Linha 1   True   True   True     False     False     False     True     True   
Linha 2   True   True   True     False     False     False     True     True   
Linha 3   True   True   True     False     False     False     True     True   
Linha0    True   True   True      True      True      True    False    False   
Linha1    True   True   True      True      True      True    False    False   
Linha2    True   True   True      True      True      True    False    False   

         coluna2  
0           True  
1           True  
2           True  
3           True  
Linha 0     True  
Linha 1     True  
Linha 2     True  
Linha 3     True  
Linha0     False  
Linha1     False  
Linha2     False

In [22]:
df4.isnull().sum()

0           7
1           7
2           7
coluna 0    7
coluna 1    7
coluna 2    7
coluna0     8
coluna1     8
coluna2     8
dtype: int64

fillna

In [23]:
df5 = df4.fillna(df4.mean())
df5

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

dropna: exclui not a number

Copiando um Data Frame:

In [24]:
df8 = df5.copy()

In [25]:
df4.dropna(inplace= True)
df4

Empty DataFrame
Columns: [0, 1, 2, coluna 0, coluna 1, coluna 2, coluna0, coluna1, coluna2]
Index: []

In [26]:
df5

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [27]:
df5.dropna(subset = [1], inplace = True)
df5

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

drop

In [28]:
df6 = df5.drop(columns = ['coluna0'])
df6

0     1     2  coluna 0  coluna 1  coluna 2  coluna1  coluna2
0         1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1         4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
2         7.0   8.0   9.0       5.5       6.5       7.5      5.0      6.0
3        10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      5.0      6.0
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      5.0      6.0
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      5.0      6.0
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      5.0      6.0
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      2.0      3.0
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      5.0      6.0
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      8.0      9.0

In [29]:
df7 = df6.drop(index = [2])
df7

0     1     2  coluna 0  coluna 1  coluna 2  coluna1  coluna2
0         1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1         4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
3        10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      5.0      6.0
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      5.0      6.0
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      5.0      6.0
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      5.0      6.0
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      2.0      3.0
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      5.0      6.0
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      8.0      9.0

valores únicos

In [30]:
df5.coluna2.unique()

array([6., 3., 9.])

In [31]:
df5.columns.unique()

Index([0, 1, 2, 'coluna 0', 'coluna 1', 'coluna 2', 'coluna0', 'coluna1',
       'coluna2'],
      dtype='object')

In [32]:
df5.index.unique()

Index([        0,         1,         2,         3, 'Linha 0', 'Linha 1',
       'Linha 2', 'Linha 3',  'Linha0',  'Linha1',  'Linha2'],
      dtype='object')

In [33]:
print (df5.coluna2.unique())

[6. 3. 9.]


In [34]:
print (df5.columns.unique())

Index([0, 1, 2, 'coluna 0', 'coluna 1', 'coluna 2', 'coluna0', 'coluna1',
       'coluna2'],
      dtype='object')


In [35]:
print (df5.index.unique())

Index([        0,         1,         2,         3, 'Linha 0', 'Linha 1',
       'Linha 2', 'Linha 3',  'Linha0',  'Linha1',  'Linha2'],
      dtype='object')


Ordenar valores

In [36]:
df8.sort_values(by ='coluna1')

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  coluna1  \
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         coluna2  
Linha0       3.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha1       6.0  
Linha2       9.0

In [37]:
df8.rename(columns = {'coluna1': 'COLUNA 1'}, inplace = True)
df8

0     1     2  coluna 0  coluna 1  coluna 2  coluna0  COLUNA 1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0       5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0       5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0       5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0       5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0       5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0       5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0       5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0       5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0       2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0       5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0       8.0   

         coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0